/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/Thomas/Documents/Tang_FPGA_Examples/4.Snake/prj/al_ip/chrom.v
 ** Date	:	2018 10 12
 ** TD version	:	4.2.511
\************************************************************/

`timescale 1ns / 1ps

module chrom ( di, waddr, we, wclk, do, raddr );

	parameter DATA_WIDTH_W = 32; 
	parameter ADDR_WIDTH_W = 10;
	parameter DATA_DEPTH_W = 1024;
	parameter DATA_WIDTH_R = 32;
	parameter ADDR_WIDTH_R = 10;
	parameter DATA_DEPTH_R = 1024;

	input  [DATA_WIDTH_W-1:0] di;
	input  [ADDR_WIDTH_W-1:0] waddr;
	input  [ADDR_WIDTH_R-1:0] raddr;
	input  wclk,we;

	output [DATA_WIDTH_R-1:0] do;



	EG_LOGIC_DRAM #(
 			.INIT_FILE("../src/rom_init.mif"),
			.DATA_WIDTH_W(DATA_WIDTH_W),
			.ADDR_WIDTH_W(ADDR_WIDTH_W),
			.DATA_DEPTH_W(DATA_DEPTH_W),
			.DATA_WIDTH_R(DATA_WIDTH_R),
			.ADDR_WIDTH_R(ADDR_WIDTH_R),
			.DATA_DEPTH_R(DATA_DEPTH_R))
		dram(
			.di(di),
			.waddr(waddr),
			.wclk(wclk),
			.we(we),
			.do(do),
			.raddr(raddr));

endmodule